theme: jekyll-theme-tactile
title: User Interface Assignment 3
description: Our task in this assignment is to build a working implementation of the front-end component of the website designed in Assignment 2. The website is written in  HTML, CSS, and Javascript, and does not have to include a working back-end (e.g. database, app server, API server, etc.) or make use of any front-end framework.
